const path=require('node:path');
const TROUT_SPECIES=['Brook Trout','Lake Trout','Rainbow Trout','Brown Trout','Splake'];
let INDEX;
function loadIndex(){if(INDEX)return INDEX;try{INDEX=require(path.join('..','data','trout-index.json'));}catch{const e=new Error('Ontario trout master index is not built');e.code='TROUT_INDEX_MISSING';throw e}return INDEX}
function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function num(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function haversineKm(a,b,c,d){const values=[a,b,c,d].map(num);if(values.some(v=>v===null))return null;const [aa,bb,cc,dd]=values,R=6371,r=x=>x*Math.PI/180,dl=r(cc-aa),dn=r(dd-bb),q=Math.sin(dl/2)**2+Math.cos(r(aa))*Math.cos(r(cc))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function normalizeTroutSpecies(value){const found=TROUT_SPECIES.find(s=>s.toLowerCase()===String(value||'').trim().toLowerCase());return found||'Brook Trout'}
function targetEvidence(lake,species){const v=lake.evidenceBySpecies?.[species];return Array.isArray(v)?v:(lake.species?.length===1?lake.evidence||[]:[])}
function targetLatestStocking(lake,species){return lake.latestStockingBySpecies?.[species]||((lake.latestStocking?.species===species)?lake.latestStocking:null)}
function recentStocking(lake,species){const y=new Date().getUTCFullYear(),s=targetLatestStocking(lake,species);return Boolean(s&&Number(s.year)>=y-5)}
function troutFit(lake,species){const ev=targetEvidence(lake,species);let score=0,reasons=[];if(ev.includes('ara_summary')){score+=50;reasons.push(`${species} appears in Ontario ARA lake-summary evidence`)}if(ev.includes('ara_survey')){score+=30;reasons.push(`${species} appears in Ontario ARA survey evidence`)}if(ev.includes('stocking')){score+=20;reasons.push(`${species} appears in Ontario stocking records`)}if(String(lake.thermalRegime||'').toLowerCase().includes('cold')){score+=6;reasons.push('Coldwater thermal regime is documented')}if(num(lake.maximumDepthM)!==null){score+=4;reasons.push(`Maximum depth ${Math.round(Number(lake.maximumDepthM))} m`)}return {score:clamp(score,0,100),reasons}}
function remoteClass(score){if(score>=82)return'Expedition';if(score>=65)return'Deep remote';if(score>=45)return'Remote';return'Easy backcountry'}
function minimumForPreset(v){return({easy:0,remote:45,deep:65,expedition:82})[String(v||'').toLowerCase()]??0}
function filterRows(filters={}){const index=loadIndex(),species=normalizeTroutSpecies(filters.species),q=String(filters.q||'').trim().toLowerCase(),explicitMin=num(filters.minRemote),minRemote=explicitMin!==null?explicitMin:minimumForPreset(filters.remote),originLat=num(filters.originLat),originLon=num(filters.originLon),maxDistance=num(filters.maxDistanceKm),minDepth=num(filters.minDepth);let rows=[];for(const lake of index.lakes){if(!lake.species?.includes(species))continue;if(filters.fmz&&String(lake.fmz||'')!==String(filters.fmz))continue;const depth=num(lake.maximumDepthM);if(minDepth!==null&&(depth===null||depth<minDepth))continue;if(filters.stocking==='recent'&&!recentStocking(lake,species))continue;if(filters.stocking==='none_recent'&&recentStocking(lake,species))continue;if(q&&!`${lake.name||''} ${lake.township||''} ${lake.municipality||''}`.toLowerCase().includes(q))continue;const remoteContext=num(lake.remote?.score),confidence=num(lake.remote?.confidence);if(remoteContext!==null&&remoteContext<minRemote)continue;if(remoteContext===null&&minRemote>0)continue;const distanceKm=originLat!==null&&originLon!==null?haversineKm(originLat,originLon,lake.latitude,lake.longitude):null;if(maxDistance!==null&&distanceKm!==null&&distanceKm>maxDistance)continue;if(maxDistance!==null&&distanceKm===null)continue;const fit=troutFit(lake,species),ev=targetEvidence(lake,species),latest=targetLatestStocking(lake,species);rows.push({...lake,targetSpecies:species,targetEvidence:ev,targetLatestStocking:latest,targetSurveyCount:lake.surveyCountBySpecies?.[species]??(ev.includes('ara_survey')?lake.surveyCount:0),troutFit:fit.score,troutReasons:fit.reasons,remoteContext,confidence,remoteClass:remoteContext===null?'Remote context unavailable':remoteClass(remoteContext),originDistanceKm:distanceKm===null?null:Math.round(distanceKm*10)/10})}return {index,species,rows}}
function sortRows(rows,sort='remote'){const s=String(sort||'remote');rows.sort((a,b)=>{if(s==='trout')return b.troutFit-a.troutFit||(b.remoteContext??-1)-(a.remoteContext??-1)||String(a.name).localeCompare(String(b.name));if(s==='distance')return(a.originDistanceKm??999999)-(b.originDistanceKm??999999)||(b.remoteContext??-1)-(a.remoteContext??-1);return(b.remoteContext??-1)-(a.remoteContext??-1)||b.troutFit-a.troutFit||(a.originDistanceKm??999999)-(b.originDistanceKm??999999)||String(a.name).localeCompare(String(b.name))});return rows}
function searchRemoteTrout(filters={},options={}){const {index,species,rows}=filterRows(filters);sortRows(rows,filters.sort);const offset=Math.max(0,Number(options.offset)||0),limit=clamp(Number(options.limit)||50,1,250),page=rows.slice(offset,offset+limit);return {lakes:page,species,candidateCount:rows.length,indexLakeCount:index.summary?.lakes||index.lakes.length,offset,listCount:page.length,hasMore:offset+page.length<rows.length,indexBuiltAt:index.builtAt,indexSummary:index.summary,indexSources:index.sources,semantics:'Results come from the complete generated Ontario trout master index for the selected target-species evidence filters. List pagination never changes candidateCount. Missing Remote Context never removes an evidenced lake unless the user explicitly selects a remoteness threshold. Remote Context is mapped-road/access planning context, not legal-access proof, solitude, fish abundance or catch probability.'}}
function remoteMap(filters={},bboxValue,maxMarkers=12000){const p=String(bboxValue||'').split(',').map(Number);if(p.length!==4||p.some(v=>!Number.isFinite(v))||p[0]>=p[2]||p[1]>=p[3])throw new Error('Invalid remote map bbox');const [west,south,east,north]=p,{index,species,rows}=filterRows(filters),mappable=rows.filter(x=>num(x.longitude)!==null&&num(x.latitude)!==null),unmappedMatching=rows.length-mappable.length,inView=mappable.filter(x=>x.longitude>=west&&x.longitude<=east&&x.latitude>=south&&x.latitude<=north),capped=inView.length>maxMarkers,markers=(capped?inView.slice(0,maxMarkers):inView).map(x=>({id:x.id,name:x.name,latitude:x.latitude,longitude:x.longitude,troutFit:x.troutFit,remoteContext:x.remoteContext,confidence:x.confidence,remoteClass:x.remoteClass,evidence:x.targetEvidence,fmz:x.fmz,thermalRegime:x.thermalRegime,latestStocking:x.targetLatestStocking}));return {markers,species,matchedInView:inView.length,displayedInView:markers.length,unmappedMatching,coverageComplete:!capped,truncatedReason:capped?'marker_safety_ceiling':null,indexLakeCount:index.summary?.lakes||index.lakes.length,indexBuiltAt:index.builtAt}}
function findInIndex(q){const s=String(q||'').trim().toLowerCase();if(!s)return[];return loadIndex().lakes.filter(x=>`${x.name||''} ${x.township||''} ${x.municipality||''}`.toLowerCase().includes(s)).slice(0,50)}
module.exports={TROUT_SPECIES,loadIndex,normalizeTroutSpecies,targetEvidence,targetLatestStocking,troutFit,remoteClass,searchRemoteTrout,remoteMap,findInIndex,num,haversineKm};
